# Generated by Django 5.2.7 on 2025-12-10 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_current_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-value']},
        ),
        migrations.RemoveField(
            model_name='auction',
            name='current_bid',
        ),
    ]
